/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GlobalRefLeak */

#ifndef _Included_GlobalRefLeak
#define _Included_GlobalRefLeak
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GlobalRefLeak
 * Method:    leakJNIGlobalRef
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_GlobalRefLeak_leakJNIGlobalRef
                                         (JNIEnv *env, jclass cls, jobject obj){
  jobject global_ref = (*env)->NewGlobalRef(env, obj);
  //(*env)->DeleteGlobalRef(env, global_ref);
}

#ifdef __cplusplus
}
#endif
#endif
